language: python
python:
- '2.7'
install: pip install -q -r requirements.txt
script: cd example && make clean && make html && cd ..
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  matrix:
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: bavo.van.achte
    password:
      secure: eTU2xAyjwVyYrpX8A4H64a6NNrDdVw4p45h0ZWzxD0Fb+4MQ6P/S6td/vn7tZGoBIbWVwzsOAaKNQLs+V2D03jtehxf12pkTw7I21B/hDgsp2DuTFM2GI/xOCcA7VoBEuEBZiMJiUGFbg7hoa/cHqHd3s97IowZ2+WaIzZoL28D0sSknyRTva63sG/oQfMWXCZ5SH4DthoFCsB3+jXhC4HKZbJzYOw2xeHHemkKmXo65a/whwsya++UuCqpo+/n+jWycjFun00sy2nE1CecQ4l0F4EpWPZgSR/a3mu4qVFW5YuZ9N1scorzZwryCREGwWRmNRRMtqNnfBcyrYvoDIRWcC1vkqv5511Qdu6ZlnHeh5FPNDMJefzzaOokpGlCLmTWcwjCprUyjXPW9xyHoHU/kdDiw5TUMmtkDvK/EgVoUNbNsCkmywbPaWzDimF3ghC0BbV2vfMCWUlBeO+C5/4HIRKJ5VKcTW9FfbuQe61tf1mN9af8j1VGXZSB6Y/aPSGQkrt0Aq+LbzMAn4Hf9z42/UGVS2/lHb7X0/p2dVEl3RG4mr8l/DtpZ5ilzF4EmFx2By+1eN24CYDshrc7momuZ+8JFUf/ECuMCi9Dv7L0UpwbQyYyoJmjyBAcCAXyZ2Db5sPuFuTm4mBeIbPe3RWmMApD8bdPq503K8g/siN4=
    on:
      branch: master
      tags: false
  - provider: pypi
    distributions: sdist
    user: bavo.van.achte
    password:
      secure: eTU2xAyjwVyYrpX8A4H64a6NNrDdVw4p45h0ZWzxD0Fb+4MQ6P/S6td/vn7tZGoBIbWVwzsOAaKNQLs+V2D03jtehxf12pkTw7I21B/hDgsp2DuTFM2GI/xOCcA7VoBEuEBZiMJiUGFbg7hoa/cHqHd3s97IowZ2+WaIzZoL28D0sSknyRTva63sG/oQfMWXCZ5SH4DthoFCsB3+jXhC4HKZbJzYOw2xeHHemkKmXo65a/whwsya++UuCqpo+/n+jWycjFun00sy2nE1CecQ4l0F4EpWPZgSR/a3mu4qVFW5YuZ9N1scorzZwryCREGwWRmNRRMtqNnfBcyrYvoDIRWcC1vkqv5511Qdu6ZlnHeh5FPNDMJefzzaOokpGlCLmTWcwjCprUyjXPW9xyHoHU/kdDiw5TUMmtkDvK/EgVoUNbNsCkmywbPaWzDimF3ghC0BbV2vfMCWUlBeO+C5/4HIRKJ5VKcTW9FfbuQe61tf1mN9af8j1VGXZSB6Y/aPSGQkrt0Aq+LbzMAn4Hf9z42/UGVS2/lHb7X0/p2dVEl3RG4mr8l/DtpZ5ilzF4EmFx2By+1eN24CYDshrc7momuZ+8JFUf/ECuMCi9Dv7L0UpwbQyYyoJmjyBAcCAXyZ2Db5sPuFuTm4mBeIbPe3RWmMApD8bdPq503K8g/siN4=
    on:
      branch: master
      tags: true

