name: Tox testing`

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install sphinx_rtd_theme
      - name: Install sphinxcontrib-wavedrom module itself
        run: pip install .
      - name: Build html document with JS rendering
        run: make -C example clean html
      - name: Build singlehtml document with JS rendering
        run: make -C example clean singlehtml
      - name: Build dirhtml document with JS rendering
        run: make -C example clean dirhtml
      - name: Build html document with prebuilt images
        run: make -C example clean html WAVEDROM_HTML_NOJSINLINE=1
      - name: Build singlehtml document with prebuilt images
        run: make -C example clean singlehtml WAVEDROM_HTML_NOJSINLINE=1
      - name: Build dirhtml document with prebuilt images
        run: make -C example clean dirhtml WAVEDROM_HTML_NOJSINLINE=1pytesttox -e py
