name: Tox testing`

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install sphinx_rtd_theme
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        run:
          - make -C example clean html
          - make -C example clean singlehtml
          - make -C example clean dirhtml
          - make -C example clean html WAVEDROM_HTML_NOJSINLINE=1
          - make -C example clean singlehtml WAVEDROM_HTML_NOJSINLINE=1
          - make -C example clean dirhtml WAVEDROM_HTML_NOJSINLINE=1pytesttox -e py
